### ISSUE TITLE
Install default/latest version of WooCommerce Blocks

### ISSUE THREAD

**Issue by nickpagz** [nielslange/woo-test-environment#1]
Great script Niels, works like a charm! 
I'd like to add a feature request to make the installation of the WooCommerce Blocks slightly easier since it takes a little bit extra time to find the latest version. I'll leave the creative direction to you, but perhaps instead of the flag being `--version=<version>`, it could be something like `--blocks=<true || version>`. The value `true` would install the latest (stable) version, or a specific version could be entered, such as `7.3.0`, for example. A bit more logic is involved in that one, but you could also set it up as two separate arguments. For clarity, the flag would be `--blocks=true`, or `--blocks=7.3.0`.

**Comment by nielslange** [comment]
Thanks for the suggestion, @nickpagz! I just implemented this change. Would you mind testing it? 😀
