### ISSUE TITLE
Automatically create and assign some attributes to products on setup

### ISSUE THREAD

**Issue by sunyatasattva** [nielslange/woo-test-environment#15]
Attributes are useful properties of products, and they are also used alongside WooCommerce Blocks “Filter products by Attribute” block. Manually creating and assigning attributes doesn't take an awful lot, but it's still time we can shave off from setup phase.

**Comment by nielslange** [comment]
@sunyatasattva I'm happy to inform you that @albarin fixed this issue. If you spin up a site now, it should contain all necessary product attributes. 😀
