### ISSUE TITLE
C&C block pages aren't created when Installing Woo Blocks via URL

### ISSUE THREAD

**Issue by tarhi-saad** [nielslange/woo-test-environment#18]
When I run the `wp woo-test-environment setup --blocks` command, the Cart and Checkout block pages are created as expected. But when installing Woo Blocks via URL (e.g. `wp woo-test-environment setup --blocks=https://github.com/woocommerce/woocommerce-blocks/files/9336360/woocommerce-gutenberg-products-block.zip`), the Cart & Checkout block pages are missing!

<img width="538" alt="image" src="https://user-images.githubusercontent.com/14235870/184674702-a407a02b-50d8-428c-92b0-57ca3c0aaf91.png">

**Comment by nielslange** [comment]
Thanks for reporting this, @tarhi-saad! I just went ahead and fixed the problem. When running
```
wp woo-test-environment setup --blocks=https://github.com/woocommerce/woocommerce-blocks/files/9336360/woocommerce-gutenberg-products-block.zip
```
you should now see the block pages such as the Cart block and the Checkout block.

**Comment by tarhi-saad** [comment]
Thank you, @nielslange, for the quick and efficient fix! 💯 I just ran a test, and it's working now! 🙌
