### ISSUE TITLE
The `Browse store.` link of the `Empty Cart` block redirect to `localhost:8889/shop/`

### ISSUE THREAD

**Issue by tarhi-saad** [nielslange/woo-test-environment#21]
When the Cart page is empty, clicking on the `Browse store.` link redirect us to the wrong URL (`localhost:8889/shop/`), see image below:

<img width="1202" alt="Screen Shot 2022-09-01 at 14 57 38" src="https://user-images.githubusercontent.com/14235870/187932779-61e0e4f6-8cf3-4629-9b5e-6d3cca3a23a0.png">

A possible solution would be to update this [line](https://github.com/nielslange/woo-test-environment/blob/trunk/command.php#L163), and replace the URL:

```html
<a href="http://localhost:8889/shop/">Browse store</a>
```

with:

```html
<a href="/shop/">Browse store</a>
```

This is a minor bug, but it would be great to fix it so that no one else thinks it's a Woo Blocks bug! I tried to debug it myself for a while. Haha

**Comment by nielslange** [comment]
Thanks for creating this issue, @tarhi-saad. I just went ahead and spun off a PR for that in #22. Would you mind reviewing it to check if it works as expected on your end?
