### ISSUE TITLE
C&C block pages aren't created when Installing Woo Blocks via URL

### ISSUE THREAD

**Issue by tarhi-saad** [nielslange/woo-test-environment#25]
This issue was reported in #18 and fixed in #19! But, for some reason, we start getting the same issue lately! 

I've tested installing Woo Blocks via URL in jurassic.ninja!

### Steps to reproduce

1. Create a jurassic.ninja website
2. SSH & run `wp package install git@github.com:nielslange/woo-test-environment.git` in the public folder.
3. Run `wp woo-test-environment setup --blocks=WOO-BLOCK-ZIP-URL`
4. Go to `pages` on your site admin page. You'll notice the missing C&C block pages:

<img width="510" alt="image" src="https://user-images.githubusercontent.com/14235870/193697074-45323f1e-5d62-4f35-b5cf-3d633d358f40.png">

**Comment by nielslange** [comment]
Thanks for reporting this, @tarhi-saad. I'll look into this.

**Comment by nielslange** [comment]
@tarhi-saad I just worked on #24. As expected, the other issue seems to have resolved this issue as a side effect. Would you mind double-checking this and closing this issue if you can no longer reproduce the problem?

**Comment by tarhi-saad** [comment]
Hi, @nielslange! I tested it again, and it's working! Excellent job! 🙌
