### ISSUE TITLE
Package doesn't work if WooCommerce Blocks folder already exists.

### ISSUE THREAD

**Issue by senadir** [nielslange/woo-test-environment#37]

**Comment by senadir** [comment]
Saw this happen when providing a zip to `--blocks`

**Comment by nielslange** [comment]
Thanks for reporting this, @senadir. Can you tell me how I can reproduce this issue?

**Comment by senadir** [comment]
Start the setup but then bail midway. This happened to me because I lost connection, but you can also just have the folder there when you start the setup.

**Comment by nielslange** [comment]
Thanks for the additional information. I just fixed this issue with https://github.com/nielslange/woo-test-environment/commit/fd85ac40924cab80b2a9254d187f28218ac393e2. Thanks again for reporting this issue. 🙌
