### ISSUE TITLE
Packages fails and exit if `woocommerce_pickup_location_settings` already set

### ISSUE THREAD

**Issue by senadir** [nielslange/woo-test-environment#38]

**Comment by senadir** [comment]
`pickup_location_pickup_locations` also fails.

**Comment by nielslange** [comment]
Thanks for reporting this, @senadir. Can you tell me how I can reproduce this issue?

**Comment by senadir** [comment]
Try setting up the option via `wp option set` or bail the setup midway and start it again

**Comment by nielslange** [comment]
Thanks for providing the steps. I just addressed this issue in https://github.com/nielslange/woo-test-environment/commit/5cfa23af4a4aa426f71b7a626ad8a3786f722ccb. Thanks for reporting this issue, though.
